version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: hackathon-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: udip
      POSTGRES_DB: hackathon_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hackathon-network

volumes:
  pgdata:
    driver: local

networks:
  hackathon-network:
    driver: bridge
